github: [follow-prince, Khushi-digi]
patreon: follow-prince
ko_fi: [https://ko-fi.com/khushiee, https://ko-fi.com/follow_prince]
custom: [https://www.buymeacoffee.com/khushie, https://ko-fi.com/khushiee, https://ko-fi.com/follow_prince]
